source:  
  source_type:  "demo"
  timing_format: "By project month number"
  timeline_precision: "Month"
text: 
  alignment:  "right"
  size: 120
  inlcude_month_top:  TRUE
lines:
  quarter:  TRUE
  wp_thickness: 6
  activity_thickness: 4
colour_palette: "Darjeeling1"

